# name: "coverage"
# on:
#   pull_request:
#     branches:
#       - development
#       - main
# jobs:
#   coverage:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: ArtiomTr/jest-coverage-report-action@v2
#
