name: "Unit Test the workflow on development branch"

on:
  push:
    branches:
      - development

jobs:
  unit-test:
    name: "Check the unit tests"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        uses: actions/github-script@v7
        with:
          script: npm test
